export const GET_TENANT_TEMPLATES_LISTING_REQUEST = 'GET_TENANT_TEMPLATES_LISTING_REQUEST';
export const GET_TENANT_TEMPLATES_LISTING_SUCCESS = 'GET_TENANT_TEMPLATES_LISTING_SUCCESS';
export const GET_TENANT_TEMPLATES_LISTING_FAILURE = 'GET_TENANT_TEMPLATES_LISTING_FAILURE';

export const GET_TENANT_TEMPLATES_REQUEST = 'GET_TENANT_TEMPLATES_REQUEST';
export const GET_TENANT_TEMPLATES_SUCCESS = 'GET_TENANT_TEMPLATES_SUCCESS';
export const GET_TENANT_TEMPLATES_FAILURE = 'GET_TENANT_TEMPLATES_FAILURE';

export const GET_TENANT_TEMPLATE_OOZIE_REQUEST = 'GET_TENANT_TEMPLATE_OOZIE_REQUEST';
export const GET_TENANT_TEMPLATE_OOZIE_SUCCESS = 'GET_TENANT_TEMPLATE_OOZIE_SUCCESS';
export const GET_TENANT_TEMPLATE_OOZIE_FAILURE = 'GET_TENANT_TEMPLATE_OOZIE_FAILURE';

export const DELETE_TENANT_TEMPLATE_OOZIE_REQUEST = 'DELETE_TENANT_TEMPLATE_OOZIE_REQUEST';
export const DELETE_TENANT_TEMPLATE_OOZIE_SUCCESS = 'DELETE_TENANT_TEMPLATE_OOZIE_SUCCESS';
export const DELETE_TENANT_TEMPLATE_OOZIE_FAILURE = 'DELETE_TENANT_TEMPLATE_OOZIE_FAILURE';

export const DELETE_TENANT_TEMPLATE_FLUME_REQUEST = 'DELETE_TENANT_TEMPLATE_FLUME_REQUEST';
export const DELETE_TENANT_TEMPLATE_FLUME_SUCCESS = 'DELETE_TENANT_TEMPLATE_FLUME_SUCCESS';
export const DELETE_TENANT_TEMPLATE_FLUME_FAILURE = 'DELETE_TENANT_TEMPLATE_FLUME_FAILURE';

export const DELETE_TENANT_TEMPLATE_REQUEST = 'DELETE_TENANT_TEMPLATE_REQUEST';
export const DELETE_TENANT_TEMPLATE_SUCCESS = 'DELETE_TENANT_TEMPLATE_SUCCESS';
export const DELETE_TENANT_TEMPLATE_FAILURE = 'DELETE_TENANT_TEMPLATE_FAILURE';

export const GET_TENANT_REQUEST = 'GET_TENANT_REQUEST';
export const GET_TENANT_SUCCESS = 'GET_TENANT_SUCCESS';
export const GET_TENANT_FAILURE = 'GET_TENANT_FAILURE';

export const POST_TENANT_REQUEST = 'POST_TENANT_REQUEST';
export const POST_TENANT_SUCCESS = 'POST_TENANT_SUCCESS';
export const POST_TENANT_FAILURE = 'POST_TENANT_FAILURE';

export const PUT_TENANT_REQUEST = 'PUT_TENANT_REQUEST';
export const PUT_TENANT_SUCCESS = 'PUT_TENANT_SUCCESS';
export const PUT_TENANT_FAILURE = 'PUT_TENANT_FAILURE';

export const DELETE_TENANT_REQUEST = 'DELETE_TENANT_REQUEST';
export const DELETE_TENANT_SUCCESS = 'DELETE_TENANT_SUCCESS';
export const DELETE_TENANT_FAILURE = 'DELETE_TENANT_FAILURE';

export const DELETE_TENANT_FORCE_REQUEST = 'DELETE_TENANT_FORCE_REQUEST';

export const PUT_TENANT_TEMPLATE_OOZIE_REQUEST = 'PUT_TENANT_TEMPLATE_OOZIE_REQUEST';
export const PUT_TENANT_TEMPLATE_OOZIE_SUCCESS = 'PUT_TENANT_TEMPLATE_OOZIE_SUCCESS';
export const PUT_TENANT_TEMPLATE_OOZIE_FAILURE = 'PUT_TENANT_TEMPLATE_OOZIE_FAILURE';

export const PUT_TENANT_TEMPLATE_FLUME_REQUEST = 'PUT_TENANT_TEMPLATE_FLUME_REQUEST';
export const PUT_TENANT_TEMPLATE_FLUME_SUCCESS = 'PUT_TENANT_TEMPLATE_FLUME_SUCCESS';
export const PUT_TENANT_TEMPLATE_FLUME_FAILURE = 'PUT_TENANT_TEMPLATE_FLUME_FAILURE';

