define(function (require) {
    "use strict";

    require('../ngModule').constant('flume.actions', {
        'UPDATE_AGENT': 'flume-UPDATE_AGENT',
        'UPDATE_SUBTYPES_METADATA': 'flume-UPDATE_SUBTYPES_METADATA',

        'LOAD_FLUME_INSTANCES_REQUEST': 'LOAD_FLUME_INSTANCES_REQUEST',
        'LOAD_FLUME_INSTANCES_SUCCESS': 'LOAD_FLUME_INSTANCES_SUCCESS',
        'LOAD_FLUME_INSTANCES_FAILURE': 'LOAD_FLUME_INSTANCES_FAILURE',

        'REFRESH_FLUME_INSTANCES_REQUEST': 'REFRESH_FLUME_INSTANCES_REQUEST',
        'REFRESH_FLUME_INSTANCES_SUCCESS': 'REFRESH_FLUME_INSTANCES_SUCCESS',
        'REFRESH_FLUME_INSTANCES_FAILURE': 'REFRESH_FLUME_INSTANCES_FAILURE',

        'CREATE_FLUME_INSTANCE_REQUEST': 'CREATE_FLUME_INSTANCE_REQUEST',
        'CREATE_FLUME_INSTANCE_SUCCESS': 'CREATE_FLUME_INSTANCE_SUCCESS',
        'CREATE_FLUME_INSTANCE_FAILURE': 'CREATE_FLUME_INSTANCE_FAILURE',

        'REMOVE_FLUME_INSTANCE_REQUEST': 'REMOVE_FLUME_INSTANCE_REQUEST',
        'REMOVE_FLUME_INSTANCE_SUCCESS': 'REMOVE_FLUME_INSTANCE_SUCCESS',
        'REMOVE_FLUME_INSTANCE_FAILURE': 'REMOVE_FLUME_INSTANCE_FAILURE',

        'START_FLUME_INSTANCE_REQUEST': 'START_FLUME_INSTANCE_REQUEST',
        'START_FLUME_INSTANCE_SUCCESS': 'START_FLUME_INSTANCE_SUCCESS',
        'START_FLUME_INSTANCE_FAILURE': 'START_FLUME_INSTANCE_FAILURE',

        'STOP_FLUME_INSTANCE_REQUEST': 'STOP_FLUME_INSTANCE_REQUEST',
        'STOP_FLUME_INSTANCE_SUCCESS': 'STOP_FLUME_INSTANCE_SUCCESS',
        'STOP_FLUME_INSTANCE_FAILURE': 'STOP_FLUME_INSTANCE_FAILURE'
    });
});
