define(function (require) {
    "use strict";

    require('../ngModule').constant('oozie.actions', {
        'LOAD_OOZIE_JOBS_REQUEST': 'LOAD_OOZIE_JOBS_REQUEST',
        'LOAD_OOZIE_JOBS_SUCCESS': 'LOAD_OOZIE_JOBS_SUCCESS',
        'LOAD_OOZIE_JOBS_FAILURE': 'LOAD_OOZIE_JOBS_FAILURE',

        'GET_OOZIE_JOB_REQUEST': 'GET_OOZIE_JOB_REQUEST',
        'GET_OOZIE_JOB_SUCCESS': 'GET_OOZIE_JOB_SUCCESS',
        'GET_OOZIE_JOB_FAILURE': 'GET_OOZIE_JOB_FAILURE',

        'CREATE_OOZIE_JOB_REQUEST': 'CREATE_OOZIE_JOB_REQUEST',
        'CREATE_OOZIE_JOB_SUCCESS': 'CREATE_OOZIE_JOB_SUCCESS',
        'CREATE_OOZIE_JOB_FAILURE': 'CREATE_OOZIE_JOB_FAILURE',

        'RUN_OOZIE_JOB_ACTION_REQUEST': 'START_OOZIE_JOB_REQUEST',
        'RUN_OOZIE_JOB_ACTION_SUCCESS': 'START_OOZIE_JOB_SUCCESS',
        'RUN_OOZIE_JOB_ACTION_FAILURE': 'START_OOZIE_JOB_FAILURE'
    });
});
