
export const GET_OOZIE_TEMPLATES_REQUEST = 'GET_OOZIE_TEMPLATES_REQUEST';
export const GET_OOZIE_TEMPLATES_SUCCESS = 'GET_OOZIE_TEMPLATES_SUCCESS';
export const GET_OOZIE_TEMPLATES_FAILURE = 'GET_OOZIE_TEMPLATES_FAILURE';

export const GET_OOZIE_COMPONENT_REQUEST = 'GET_OOZIE_COMPONENT_REQUEST';
export const GET_OOZIE_COMPONENT_SUCCESS = 'GET_OOZIE_COMPONENT_SUCCESS';
export const GET_OOZIE_COMPONENT_FAILURE = 'GET_OOZIE_COMPONENT_FAILURE';

export const GET_OOZIE_COMPONENT_FILES_REQUEST = 'GET_OOZIE_COMPONENT_FILES_REQUEST';
export const GET_OOZIE_COMPONENT_FILES_SUCCESS = 'GET_OOZIE_COMPONENT_FILES_SUCCESS';
export const GET_OOZIE_COMPONENT_FILES_FAILURE = 'GET_OOZIE_COMPONENT_FILES_FAILURE';

export const POST_OOZIE_TEMPLATE_REQUEST = 'POST_OOZIE_TEMPLATE_REQUEST';
export const POST_OOZIE_TEMPLATE_SUCCESS = 'POST_OOZIE_TEMPLATE_SUCCESS';
export const POST_OOZIE_TEMPLATE_FAILURE = 'POST_OOZIE_TEMPLATE_FAILURE';


export const GET_OOZIE_DEPLOYED_COMPONENTS_REQUEST = 'GET_OOZIE_DEPLOYED_COMPONENTS_REQUEST';
export const GET_OOZIE_DEPLOYED_COMPONENTS_SUCCESS = 'GET_OOZIE_DEPLOYED_COMPONENTS_SUCCESS';
export const GET_OOZIE_DEPLOYED_COMPONENTS_FAILURE = 'GET_OOZIE_DEPLOYED_COMPONENTS_FAILURE';
