CREATE TABLE OOZIE_ACCESS (
  ID          INT(11)      NOT NULL AUTO_INCREMENT,
  PLATFORM_ID INT(11)      NOT NULL,
  CLUSTER_ID  VARCHAR(512) NOT NULL,
  SERVICE_ID  VARCHAR(512) NOT NULL,
  API_ID      INT(11)      NOT NULL,
  KERBERIZED  BOOLEAN,
  ROOT_PATH   VARCHAR(512),
  PRIMARY KEY (ID),
  CONSTRAINT OOZIE_ACCESS__API_FK FOREIGN KEY (API_ID) REFERENCES API (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT OOZIE_ACCESS_PLATFORM_FK FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
