CREATE TABLE CLUSTER (
  PLATFORM_ID INT      NOT NULL,
  CLUSTER_ID  VARCHAR(512) NOT NULL,
  NAME  VARCHAR(2048) NOT NULL,
  PRIMARY KEY (PLATFORM_ID, CLUSTER_ID),
  CONSTRAINT CLUSTER_PLATFORM_FK FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
