ALTER TABLE OOZIE_WORKFLOW
  CHANGE COLUMN _VERSION SCHEMA_VERSION VARCHAR(64);
ALTER TABLE OOZIE_WORKFLOW
  CHANGE COLUMN TITLE NAME VARCHAR(64);
ALTER TABLE OOZIE_WORKFLOW
  ADD COLUMN COMPONENT_VERSION VARCHAR(64);
ALTER TABLE OOZIE_WORKFLOW
  ADD COLUMN RENDERED_NAME VARCHAR(128) DEFAULT '' AFTER NAME;
UPDATE OOZIE_WORKFLOW SET RENDERED_NAME = NAME;

ALTER TABLE OOZIE_TEMPLATE
    CHANGE COLUMN VERSION SCHEMA_VERSION VARCHAR(64);
ALTER TABLE OOZIE_TEMPLATE
    ADD COLUMN SCHEMA_NAME VARCHAR(64) AFTER ID;
ALTER TABLE OOZIE_TEMPLATE
    ADD COLUMN RENDERED_SCHEMA_NAME VARCHAR(128) DEFAULT '' AFTER SCHEMA_NAME;
UPDATE OOZIE_TEMPLATE SET RENDERED_SCHEMA_NAME = SCHEMA_NAME;