CREATE TABLE API (
  ID        INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TYPE      VARCHAR(256) NOT NULL,
  VERSION   VARCHAR(256),
  HOST      VARCHAR(256) NOT NULL,
  PORT      INT          NOT NULL,
  PROTOCOL  VARCHAR(50)  NOT NULL DEFAULT 'http',
  USER_NAME VARCHAR(256),
  PASSWORD  VARCHAR(256),
  KEY_FILE  VARCHAR(512)
);


CREATE TABLE SESSION (
  TOKEN     VARCHAR(64)  NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR(256) NOT NULL,
  TIMESTAMP TIMESTAMP
);
CREATE INDEX IND_SESSION ON SESSION (USER_NAME);


CREATE TABLE PROPERTY (
  _KEY   VARCHAR(512)  NOT NULL PRIMARY KEY,
  _VALUE VARCHAR(8192) NOT NULL
);


CREATE TABLE ARTIFACTORY (
  ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TYPE        VARCHAR(128),
  PRIORITY    INT,
  DESCRIPTION VARCHAR(2048),
  PROTOCOL    VARCHAR(10),
  ROOT        VARCHAR(2048),
  API_ID      INT NOT NULL,
  FOREIGN KEY ARTIFACTORY_API_FK (API_ID) REFERENCES API (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);