ALTER TABLE OOZIE_WORKFLOW
  MODIFY COLUMN SCHEMA_VERSION VARCHAR(64) DEFAULT '';
UPDATE OOZIE_WORKFLOW SET SCHEMA_VERSION = '' WHERE SCHEMA_VERSION IS NULL;

ALTER TABLE OOZIE_WORKFLOW
  MODIFY COLUMN NAME VARCHAR(64) DEFAULT '';
UPDATE OOZIE_WORKFLOW SET NAME = '' WHERE NAME IS NULL;

ALTER TABLE OOZIE_WORKFLOW
  MODIFY COLUMN COMPONENT_VERSION VARCHAR(64) DEFAULT '';
UPDATE OOZIE_WORKFLOW SET COMPONENT_VERSION = '' WHERE COMPONENT_VERSION IS NULL;

ALTER TABLE OOZIE_WORKFLOW
  MODIFY RENDERED_NAME VARCHAR(128) DEFAULT '';
UPDATE OOZIE_WORKFLOW SET RENDERED_NAME = '' WHERE RENDERED_NAME IS NULL;


ALTER TABLE OOZIE_TEMPLATE
  MODIFY SCHEMA_VERSION VARCHAR(64) DEFAULT '';
UPDATE OOZIE_TEMPLATE SET SCHEMA_VERSION = '' WHERE SCHEMA_VERSION IS NULL;

ALTER TABLE OOZIE_TEMPLATE
  MODIFY SCHEMA_NAME VARCHAR(64) DEFAULT '';
UPDATE OOZIE_TEMPLATE SET SCHEMA_NAME = '' WHERE SCHEMA_NAME IS NULL;

ALTER TABLE OOZIE_TEMPLATE
  MODIFY RENDERED_SCHEMA_NAME VARCHAR(128) DEFAULT '';
UPDATE OOZIE_TEMPLATE SET RENDERED_SCHEMA_NAME = '' WHERE RENDERED_SCHEMA_NAME IS NULL;
