ALTER TABLE HDFS DROP FOREIGN KEY HDFS_PLATFORM_FK;
ALTER TABLE HDFS DROP INDEX HDFS_PLATFORM_FK;

ALTER TABLE HDFS ADD CONSTRAINT HDFS_CLUSTER_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID)
  REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE ON UPDATE CASCADE;

