DROP TABLE OOZIE_WORKFLOW;

CREATE TABLE OOZIE_WORKFLOW (
  PLATFORM_ID INT(11) NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  PATH     VARCHAR(512) NOT NULL,
  NAME    VARCHAR(128) NOT NULL,
  RENDERED_NAME VARCHAR(128) DEFAULT '',
  SCHEMA_VERSION VARCHAR(16)  NOT NULL,
  CONSTRAINT WF_PK PRIMARY KEY (PLATFORM_ID, CLUSTER_ID, PATH),
  CONSTRAINT WF_CLUSTER_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
