CREATE TABLE OOZIE_JOB (
  PLATFORM_ID INT(11)      NOT NULL,
  CLUSTER_ID  VARCHAR(512) NOT NULL,
  JOB_ID  VARCHAR(64) NOT NULL,
  START_TIME DATETIME NOT NULL,
  APP_NAME  VARCHAR(512) NOT NULL,
  APP_PATH  VARCHAR(750) NOT NULL,
  PARENT_ID  VARCHAR(64),
  PRIMARY KEY (PLATFORM_ID, CLUSTER_ID, JOB_ID),
  CONSTRAINT OOZIE_JOB_CLUSTER_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX OOZIE_JOB_APP_PATH_KEY ON OOZIE_JOB(PLATFORM_ID, APP_PATH, START_TIME);

ALTER TABLE CLUSTER
  ADD COLUMN HDFS_INDEXING DATETIME;
ALTER TABLE CLUSTER
  ADD COLUMN OOZIE_JOB_INDEXING DATETIME;
