ALTER TABLE OOZIE_ACCESS DROP COLUMN KERBERIZED;
ALTER TABLE HDFS_ACCESS DROP COLUMN KERBERIZED, DROP COLUMN IMPERSONATED;

CREATE TABLE CLUSTER_SETTINGS (
  PLATFORM_ID INT(11) NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  KERBERIZED BOOLEAN NOT NULL DEFAULT FALSE,
  REALM VARCHAR(255) NULL,
  CONSTRAINT CLUSTER_SETTINGS_PK PRIMARY KEY (PLATFORM_ID, CLUSTER_ID),
  CONSTRAINT CLUSTER_SETTINGS_CLUSTER_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)






