CREATE TABLE PLATFORM (
  ID          INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TYPE        VARCHAR(100)  NOT NULL,
  VERSION     VARCHAR(100)  NOT NULL,
  DESCRIPTION VARCHAR(2048) NOT NULL,
  API_ID      INT           NOT NULL,
  FOREIGN KEY PLATFORM_API_FK (API_ID) REFERENCES API (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE HDFS (
  ID           INT(11)      NOT NULL AUTO_INCREMENT,
  PLATFORM_ID  INT(11)      NOT NULL,
  CLUSTER_ID   VARCHAR(256) NOT NULL,
  SERVICE_ID   VARCHAR(256) NOT NULL,
  API_ID       INT(11)      NOT NULL,
  KERBERIZED   BOOLEAN,
  IMPERSONATED BOOLEAN      NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  KEY HDFS_API_FK (API_ID),
  KEY HDFS_PLATFORM_FK (PLATFORM_ID),
  CONSTRAINT HDFS_API_FK FOREIGN KEY (API_ID) REFERENCES API (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT HDFS_PLATFORM_FK FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE OOZIE_WORKFLOW (
  HDFS_ID  INT(11)      NOT NULL,
  PATH     VARCHAR(512) NOT NULL,
  TITLE    VARCHAR(128) NOT NULL,
  _VERSION VARCHAR(16)  NOT NULL,
  PRIMARY KEY `PKEY` (`HDFS_ID`, `PATH`),
  KEY WORKFLOW_HDFS_FK (HDFS_ID),
  CONSTRAINT WORKFLOW_HDFS_FK FOREIGN KEY (HDFS_ID) REFERENCES HDFS (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

