ALTER TABLE USER
  DROP COLUMN TYPE,
  DROP COLUMN PASSWORD,
  ADD COLUMN OWNER VARCHAR(256) NULL,
  DROP INDEX USER_NAME_TYPE_UK;

ALTER TABLE KEY_FILE
  ADD COLUMN OWNER VARCHAR(256) NULL,
  DROP INDEX KEY_FILE__PATH_TYPE;





