DROP TABLE USER_SETTINGS;

CREATE TABLE USER_SETTINGS (
  USER  VARCHAR(256) PRIMARY KEY,
  SETTINGS VARCHAR(2048),
  HDFS_USER_ID INT,
  OOZIE_USER_ID INT,
  CONSTRAINT SETTINGS_HDFS_USER_FK FOREIGN KEY (HDFS_USER_ID) REFERENCES USER (ID) ON DELETE SET NULL,
  CONSTRAINT SETTINGS_OOZIE_USER_FK FOREIGN KEY (OOZIE_USER_ID) REFERENCES USER (ID) ON DELETE SET NULL
);






