CREATE TABLE METRICS_ASSIGNMENT (
  ID int(11) NOT NULL AUTO_INCREMENT,
  COMPONENT_PATH VARCHAR(256) NOT NULL,
  NODE_ID varchar(256) NOT NULL,
  VALUE varchar(256) DEFAULT '',
  TITLE varchar(256) NOT NULL,
  COLOR varchar(256) DEFAULT NULL,
  PRIMARY KEY (ID)
)