CREATE TABLE CLUSTER_SERVICE (
  PLATFORM_ID INT NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  SERVICE_ID VARCHAR(256) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  TYPE VARCHAR(256) NOT NULL,
  LAST_UPDATE LONG NOT NULL,
  PRIMARY KEY (PLATFORM_ID, CLUSTER_ID, SERVICE_ID),
  CONSTRAINT FLUME_COMPONENT_CLUSTER_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE
)