CREATE TABLE TENANT (
  ID          INT          NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(512) NOT NULL,
  DESCRIPTION VARCHAR(2048),
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX TENANT_NAME_UK ON TENANT (NAME);


CREATE TABLE TEMPLATE (
  ID          INT           NOT NULL AUTO_INCREMENT,
  TENANT_ID   INT           NOT NULL,
  TYPE        VARCHAR(128)  NOT NULL,
  PATH        VARCHAR(2048) NOT NULL,
  NAME        VARCHAR(128)  NOT NULL,
  VERSION     VARCHAR(512),
  DESCRIPTION VARCHAR(2048),
  MODIFIED    TIMESTAMP     NOT NULL,
  ACTIVE      BOOLEAN,
  PRIMARY KEY (ID),
  FOREIGN KEY TEMPLATE_TENANT_FK(TENANT_ID) REFERENCES TENANT (ID)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX TEMPLATE_TITLE_VERSION_KEY ON TEMPLATE (NAME, VERSION);


CREATE TABLE OOZIE_NODE_TEMPLATE (
  ID        INT         NOT NULL,
  NODE_TYPE VARCHAR(32) NOT NULL,
  VERSION   VARCHAR(16) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY OOZIE_NODE_TEMPLATE_FK(ID) REFERENCES TEMPLATE (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE OOZIE_TEMPLATE (
  ID      INT         NOT NULL,
  VERSION VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY OOZIE_TEMPLATE_FK(ID) REFERENCES TEMPLATE (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE FLUME_TEMPLATE (
  ID         INT NOT NULL,
  AGENT_NAME VARCHAR(256),
  PRIMARY KEY (ID),
  FOREIGN KEY FLUME_TEMPLATE_FK(ID) REFERENCES TEMPLATE (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE FLUME_ELEMENT_TEMPLATE (
  ID              INT          NOT NULL AUTO_INCREMENT,
  ELEMENT_TYPE    VARCHAR(32)  NOT NULL,
  ELEMENT_SUBTYPE VARCHAR(512) NOT NULL,
  AGENT_NAME      VARCHAR(512) NOT NULL,
  NODE_NAME       VARCHAR(512) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY FLUME_ELEMENT_TEMPLATE_FK(ID) REFERENCES TEMPLATE (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


