CREATE TABLE PLATFORM_INSTALLATION (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PLATFORM_ID INT,
  CLUSTER_NAME VARCHAR(255) NOT NULL,
  DISTR_TYPE VARCHAR(255) NOT NULL,
  DISTR_VERSION VARCHAR(255) NOT NULL,
  PROVIDER VARCHAR(255) NOT NULL,
  `STATUS` VARCHAR(255) NOT NULL,
  CONSTRAINT PLATFORM_INSTALLATION_PLATFORM_FK FOREIGN KEY (PLATFORM_ID)
    REFERENCES PLATFORM (ID) ON DELETE CASCADE
)