CREATE TABLE JOB_HISTORY_ACCESS (
  PLATFORM_ID INT(11) NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  HOST VARCHAR(256) NOT NULL,
  PORT INT(11) NOT NULL,
  CONSTRAINT JOB_HISTORY_ACCESS_PK PRIMARY KEY (PLATFORM_ID, CLUSTER_ID),
  CONSTRAINT JOB_HISTORY_CLUSTER_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE ON UPDATE CASCADE
)

