CREATE TABLE FLUME_DEPLOYMENT (
  PLATFORM_ID INT NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  SERVICE_ID VARCHAR(512) NOT NULL,
  COMPONENT_ID VARCHAR(512) NOT NULL,
  TEMPLATE_ID INT(11) NOT NULL,
  DATE DATETIME NOT NULL,
  PRIMARY KEY (PLATFORM_ID, CLUSTER_ID, SERVICE_ID, COMPONENT_ID, TEMPLATE_ID),
  CONSTRAINT FLUME_DEPLOYMENT_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID, SERVICE_ID, COMPONENT_ID) REFERENCES FLUME_COMPONENT (PLATFORM_ID, CLUSTER_ID, SERVICE_ID, COMPONENT_ID) ON DELETE CASCADE,
  CONSTRAINT FLUME_TEMPLATE_DEPLOYMENT_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE (ID) ON DELETE CASCADE
)