CREATE TABLE OOZIE_DEPLOYMENT (
  PLATFORM_ID INT NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  PATH VARCHAR(512) NOT NULL,
  TEMPLATE_ID INT(11) NOT NULL,
  DATE DATETIME NOT NULL,
  PRIMARY KEY (PLATFORM_ID, CLUSTER_ID, PATH, TEMPLATE_ID),
  CONSTRAINT WORKFLOW_DEPLOYMENT_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID, PATH) REFERENCES OOZIE_WORKFLOW (PLATFORM_ID, CLUSTER_ID, PATH) ON DELETE CASCADE,
  CONSTRAINT TEMPLATE_DEPLOYMENT_FK FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE (ID) ON DELETE CASCADE
)