CREATE TABLE CLUSTER_CONFIG_UPDATE (
  PLATFORM_ID INT NOT NULL,
  CLUSTER_ID VARCHAR(256) NOT NULL,
  DATE DATETIME NOT NULL,
  SUCCESS BOOLEAN,
  PRIMARY KEY (PLATFORM_ID, CLUSTER_ID),
  CONSTRAINT CLUSTER_CONFIG_UPDATE_FK FOREIGN KEY (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE
)