ALTER TABLE KEY_FILE DROP COLUMN DESCRIPTION;
ALTER TABLE KEY_FILE DROP COLUMN PATH;
ALTER TABLE KEY_FILE ADD COLUMN NAME VARCHAR(512) NOT NULL;
ALTER TABLE KEY_FILE ADD COLUMN PLATFORM_ID INT(11) NULL;
ALTER TABLE KEY_FILE ADD COLUMN CLUSTER_ID VARCHAR(512) NULL;
ALTER TABLE KEY_FILE ADD FOREIGN KEY KEY_PLATFORM__FK (PLATFORM_ID) REFERENCES PLATFORM (ID) ON DELETE CASCADE ;
ALTER TABLE KEY_FILE ADD FOREIGN KEY KEY_CLUSTER__FK (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE;