ALTER TABLE USER ADD COLUMN TEAM VARCHAR(512) NULL;
ALTER TABLE USER ADD COLUMN PLATFORM_ID INT(11) NULL;
ALTER TABLE USER ADD COLUMN CLUSTER_ID VARCHAR(512) NULL;
ALTER TABLE USER ADD FOREIGN KEY USER_PLATFORM__FK (PLATFORM_ID) REFERENCES PLATFORM (ID) ON DELETE CASCADE ;
ALTER TABLE USER ADD FOREIGN KEY USER_CLUSTER__FK (PLATFORM_ID, CLUSTER_ID) REFERENCES CLUSTER (PLATFORM_ID, CLUSTER_ID) ON DELETE CASCADE;