INSERT INTO FEATURE_ROLES (FEATURE, ROLE) VALUES ('APP_SETTINGS_READ', 'admin');
INSERT INTO FEATURE_ROLES (FEATURE, ROLE) VALUES ('APP_SETTINGS_WRITE', 'admin');
INSERT INTO FEATURE_ROLES (FEATURE, ROLE) VALUES ('USER_SETTINGS_READ', 'admin');
INSERT INTO FEATURE_ROLES (FEATURE, ROLE) VALUES ('USER_SETTINGS_WRITE', 'admin');
