CREATE DATABASE HW;
CREATE USER 'hw' IDENTIFIED BY 'hw';
GRANT ALL PRIVILEGES ON HW.* TO 'hw'@'localhost' IDENTIFIED BY 'hw';
GRANT ALL PRIVILEGES ON HW.* TO 'hw'@'%' IDENTIFIED BY 'hw';

FLUSH PRIVILEGES;